### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by lucasew** [lucasew/limpazap#3]
Eu sou um zero a esquerda basicamente com design gráfico.

Essa issue é para sugestões de logos para o app.

**Comment by mandyellow** [comment]
Olá, tudo bom? Fiz uma opção de logo pra ajudar no seu projeto! Coloquei os ícones para a stores em duas cores para escolher. Se gostar, por favor me avise para eu abrir uma PR com o PNG e o SVG para você. 🦊 

![image](https://user-images.githubusercontent.com/30158643/94852002-9ff35400-03ff-11eb-8b27-855413773727.png)

**Comment by lucasew** [comment]
Não to sabendo lidar, desculpa. 

Primeira contribuição de arte ou código que eu tive em projeto meu.

Muito obrigado.  Pode mandar a PR se não for incomodo. Se quiser pode criar uma pasta media na raiz e botar os arquivos lá que depois eu organizo as coisas no lugar como a logo na APK e o banner no README.

**Comment by mandyellow** [comment]
Fico feliz que tenha gostado haha espero ter ajudado 🦊 Se precisar de algum outro formato, me avisa que eu subo pra você.
