### ISSUE TITLE
More translations

### ISSUE THREAD

**Issue by WPFilmmaker** [lucasew/limpazap#7]
First of all obrigado for this app! It is really needed!

I saw on your ticket on gitlab that you don't intend to make the app international, and from what I understood it is available only in Portuguese and English. However with a search googling you easily find out that whatsapp is the most popular messenger in over one hundred countries. Moreover google play is full of similar apps (closed source) full of trackers and requiring a lot of permissions (I checked on exodus one with over 1m downloads and it had 6 trackers and required 10 permissions..)

Therefore I feel there is demand for this app way beyond Brazil.

I think the app has few strings of text and would like to offer to translate the app in Italian, (I might be able to translate also in a few other languages).
Would you accept?

**Comment by lucasew** [comment]
I am planning to replace the text for icons as much as I can. First I want to launch it on f-droid so I am working to migrate it to the latest flutter version (Google being Google).

I think it will make it easier for people around the world, even that people that can't read and send only audios using WhatsApp (these people exist and I know one).

Maybe I can remove completely the toast logic in the future for something like that swipe out animation when deleting everything.

**Comment by lucasew** [comment]
Solved on 3.x
